#!/bin/bash
regexPat='[0-2][0-9]:[0-5][0-9]:[0-5][0-9]'
echo "insert a command > " 
read command
echo "insert a time > "
read time
now=$(date +"%T")
timeInSecond=$(echo $time | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3}')
nowInSecond=$(echo $now | awk -F: '{ print ($1 * 3600) + ($2 * 60) + $3}')
while true; do
        if [[ $time =~ $regexPat ]]; then
                if [[ "$time" == $now ]];then
                        $command
                elif [[ "$time" < $now ]];then
                        ((num=$nowInSecond - $timeInSecond + $nowInSecond))
			echo "wait for $num time to execute"
			sleep $num
                        $command
			break
                elif [[ "$time" > $now ]];then
                        ((num=$timeInSecond - $nowInSecond))
			echo "wait for $num time to execute"
			sleep $num
                        $command
			break
                else
                        echo "somthing you insert got problem"
			break
                fi
        else
                echo "the format of time should be HH:MM:SS >"
		echo "insert a time > "
  		read time
		continue
	fi
done 
